### ISSUE TITLE
Univ_Codes?

### ISSUE THREAD

**Issue by valonsodev** [StephanJ98/StephanJ98#1]
No es la mejor manera de contactar pero tampoco se me ocurría otra. He visto que eliminaste el repo de Univ_Codes. ¿No tendrás una copia por ahí no? O si está privado hacerlo público un día para poder clonarlo.

**Comment by StephanJ98** [comment]
Hola. En un rato voy a poner un par de mensajes por los grupos universitarios y ya comneto hay todo lo que esta pasando.
